

#define MOV_CMD "mov"
#define CMP_CMD "cmp"
#define ADD_CMD "add"
#define SUB_CMD "sub"
#define LEA_CMD "lea"
#define CLR_CMD "clr"
#define NOT_CMD "not"
#define INC_CMD "inc"
#define DEC_CMD "dec"
#define JMP_CMD "jmp"
#define BNE_CMD "bne"
#define RED_CMD "red"
#define PRN_CMD "prn"
#define JSR_CMD "jsr"
#define RTS_CMD "rts"
#define STOP_CMD "stop"

#define REG_0 "r0"
#define REG_1 "r1"
#define REG_2 "r2"
#define REG_3 "r3"
#define REG_4 "r4"
#define REG_5 "r5"
#define REG_6 "r6"
#define REG_7 "r7"

#define DATA ".data"
#define STRING ".string"
#define EXTERN ".extern"
#define ENTRY ".entry"
